"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: zach.z.liu@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import airflow_python_sdk
from airflow_python_sdk.model.task_state import TaskState
globals()['TaskState'] = TaskState
from airflow_python_sdk.model.dag_run import DAGRun


class TestDAGRun(unittest.TestCase):
    """DAGRun unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDAGRun(self):
        """Test DAGRun"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DAGRun()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
