"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: dev@airflow.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.extra_link import ExtraLink
globals()['ExtraLink'] = ExtraLink
from openapi_client.model.extra_link_collection import ExtraLinkCollection


class TestExtraLinkCollection(unittest.TestCase):
    """ExtraLinkCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExtraLinkCollection(self):
        """Test ExtraLinkCollection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExtraLinkCollection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
