"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: dev@airflow.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.class_reference import ClassReference
globals()['ClassReference'] = ClassReference
from openapi_client.model.task_extra_links import TaskExtraLinks


class TestTaskExtraLinks(unittest.TestCase):
    """TaskExtraLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskExtraLinks(self):
        """Test TaskExtraLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskExtraLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
