"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: zach.z.liu@gmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import airflow_python_sdk
from airflow_python_sdk.api.dag_run_api import DAGRunApi  # noqa: E501


class TestDAGRunApi(unittest.TestCase):
    """DAGRunApi unit test stubs"""

    def setUp(self):
        self.api = DAGRunApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_dag_run(self):
        """Test case for delete_dag_run

        Delete a DAG Run  # noqa: E501
        """
        pass

    def test_get_dag_run(self):
        """Test case for get_dag_run

        Get a DAG Run  # noqa: E501
        """
        pass

    def test_get_dag_runs(self):
        """Test case for get_dag_runs

        Get all DAG Runs  # noqa: E501
        """
        pass

    def test_update_dag_run(self):
        """Test case for update_dag_run

        Update a DAG Run  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
