"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: zach.z.liu@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import airflow_python_sdk
from airflow_python_sdk.model.config_section import ConfigSection
globals()['ConfigSection'] = ConfigSection
from airflow_python_sdk.model.config import Config


class TestConfig(unittest.TestCase):
    """Config unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfig(self):
        """Test Config"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Config()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
