"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: zach.z.liu@gmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import airflow_python_sdk
from airflow_python_sdk.api.dag_api import DAGApi  # noqa: E501


class TestDAGApi(unittest.TestCase):
    """DAGApi unit test stubs"""

    def setUp(self):
        self.api = DAGApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_dag(self):
        """Test case for get_dag

        Get basic information about a DAG  # noqa: E501
        """
        pass

    def test_get_dag_source(self):
        """Test case for get_dag_source

        Get source code using file token  # noqa: E501
        """
        pass

    def test_get_dag_structure(self):
        """Test case for get_dag_structure

        Get simplified representation of DAG.  # noqa: E501
        """
        pass

    def test_get_dags(self):
        """Test case for get_dags

        Get all DAGs  # noqa: E501
        """
        pass

    def test_get_task(self):
        """Test case for get_task

        Get simplified representation of a task.  # noqa: E501
        """
        pass

    def test_get_tasks(self):
        """Test case for get_tasks

        Get tasks for DAG  # noqa: E501
        """
        pass

    def test_update_dag(self):
        """Test case for update_dag

        Update the specific DAG  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
