"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: zach.z.liu@gmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import airflow_python_sdk
from airflow_python_sdk.api.x_com_api import XComApi  # noqa: E501


class TestXComApi(unittest.TestCase):
    """XComApi unit test stubs"""

    def setUp(self):
        self.api = XComApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_x_com_value(self):
        """Test case for delete_x_com_value

        Delete an XCom entry  # noqa: E501
        """
        pass

    def test_get_x_com_value(self):
        """Test case for get_x_com_value

        Get an XCom entry  # noqa: E501
        """
        pass

    def test_get_x_com_values(self):
        """Test case for get_x_com_values

        Get all XCom values  # noqa: E501
        """
        pass

    def test_update_x_com_value(self):
        """Test case for update_x_com_value

        Update an XCom entry  # noqa: E501
        """
        pass

    def test_update_x_com_values(self):
        """Test case for update_x_com_values

        Create an XCom entry  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
