"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: dev@airflow.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.task_state import TaskState
globals()['TaskState'] = TaskState
from openapi_client.model.dag_run import DAGRun


class TestDAGRun(unittest.TestCase):
    """DAGRun unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDAGRun(self):
        """Test DAGRun"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DAGRun()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
