"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: dev@airflow.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.x_com_collection_item import XComCollectionItem
globals()['XComCollectionItem'] = XComCollectionItem
from openapi_client.model.x_com_collection import XComCollection


class TestXComCollection(unittest.TestCase):
    """XComCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testXComCollection(self):
        """Test XComCollection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = XComCollection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
