"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: zach.z.liu@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import airflow_python_sdk
from airflow_python_sdk.model.dag_structure import DagStructure
globals()['DagStructure'] = DagStructure
from airflow_python_sdk.model.dag_structure_collection import DagStructureCollection


class TestDagStructureCollection(unittest.TestCase):
    """DagStructureCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDagStructureCollection(self):
        """Test DagStructureCollection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DagStructureCollection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
