"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: dev@airflow.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.dag_structure import DagStructure
globals()['DagStructure'] = DagStructure
from openapi_client.model.dag_structure_collection import DagStructureCollection


class TestDagStructureCollection(unittest.TestCase):
    """DagStructureCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDagStructureCollection(self):
        """Test DagStructureCollection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DagStructureCollection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
