"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: dev@airflow.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.sla_miss import SLAMiss
from openapi_client.model.task_state import TaskState
globals()['SLAMiss'] = SLAMiss
globals()['TaskState'] = TaskState
from openapi_client.model.task_instance import TaskInstance


class TestTaskInstance(unittest.TestCase):
    """TaskInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskInstance(self):
        """Test TaskInstance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskInstance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
