"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: dev@airflow.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.task_instance import TaskInstance
globals()['TaskInstance'] = TaskInstance
from openapi_client.model.task_instance_collection import TaskInstanceCollection


class TestTaskInstanceCollection(unittest.TestCase):
    """TaskInstanceCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskInstanceCollection(self):
        """Test TaskInstanceCollection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskInstanceCollection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
