"""
    Airflow API (Stable)
    Apache Airflow management API.  # noqa: E501
    The version of the OpenAPI document: 1.0.0
    Contact: zach.z.liu@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import airflow_python_sdk
from airflow_python_sdk.model.update_task_instances_state import UpdateTaskInstancesState


class TestUpdateTaskInstancesState(unittest.TestCase):
    """UpdateTaskInstancesState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateTaskInstancesState(self):
        """Test UpdateTaskInstancesState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateTaskInstancesState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
