"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: dev@airflow.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.class_reference import ClassReference
from openapi_client.model.color import Color
from openapi_client.model.task_extra_links import TaskExtraLinks
from openapi_client.model.time_delta import TimeDelta
from openapi_client.model.trigger_rule import TriggerRule
from openapi_client.model.weight_rule import WeightRule
globals()['ClassReference'] = ClassReference
globals()['Color'] = Color
globals()['TaskExtraLinks'] = TaskExtraLinks
globals()['TimeDelta'] = TimeDelta
globals()['TriggerRule'] = TriggerRule
globals()['WeightRule'] = WeightRule
from openapi_client.model.task import Task


class TestTask(unittest.TestCase):
    """Task unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTask(self):
        """Test Task"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Task()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
