"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: zach.z.liu@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import airflow_python_sdk
from airflow_python_sdk.model.schedule_interval import ScheduleInterval
from airflow_python_sdk.model.tag import Tag
globals()['ScheduleInterval'] = ScheduleInterval
globals()['Tag'] = Tag
from airflow_python_sdk.model.dag import DAG


class TestDAG(unittest.TestCase):
    """DAG unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDAG(self):
        """Test DAG"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DAG()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
