"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: dev@airflow.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.task import Task
globals()['Task'] = Task
from openapi_client.model.task_collection import TaskCollection


class TestTaskCollection(unittest.TestCase):
    """TaskCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskCollection(self):
        """Test TaskCollection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskCollection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
