"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: zach.z.liu@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import airflow_python_sdk
from airflow_python_sdk.model.task_state import TaskState


class TestTaskState(unittest.TestCase):
    """TaskState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskState(self):
        """Test TaskState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
