"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: zach.z.liu@gmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import airflow_python_sdk
from airflow_python_sdk.api.import_error_api import ImportErrorApi  # noqa: E501


class TestImportErrorApi(unittest.TestCase):
    """ImportErrorApi unit test stubs"""

    def setUp(self):
        self.api = ImportErrorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_import_error(self):
        """Test case for delete_import_error

        Delete an import error  # noqa: E501
        """
        pass

    def test_get_import_error(self):
        """Test case for get_import_error

        Get an import errors  # noqa: E501
        """
        pass

    def test_get_import_errors(self):
        """Test case for get_import_errors

        Get all import errors  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
