"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: dev@airflow.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.dag import DAG
globals()['DAG'] = DAG
from openapi_client.model.dag_collection import DAGCollection


class TestDAGCollection(unittest.TestCase):
    """DAGCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDAGCollection(self):
        """Test DAGCollection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DAGCollection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
