"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: zach.z.liu@gmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import airflow_python_sdk
from airflow_python_sdk.api.variable_api import VariableApi  # noqa: E501


class TestVariableApi(unittest.TestCase):
    """VariableApi unit test stubs"""

    def setUp(self):
        self.api = VariableApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_variable(self):
        """Test case for create_variable

        Create a variables  # noqa: E501
        """
        pass

    def test_delete_variable(self):
        """Test case for delete_variable

        Delete variable  # noqa: E501
        """
        pass

    def test_get_variable(self):
        """Test case for get_variable

        Get a variables by id  # noqa: E501
        """
        pass

    def test_get_variables(self):
        """Test case for get_variables

        Get all variables  # noqa: E501
        """
        pass

    def test_lookup_variable(self):
        """Test case for lookup_variable

        Get variable using its key.  # noqa: E501
        """
        pass

    def test_update_variable(self):
        """Test case for update_variable

        Update a variable by id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
