"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: zach.z.liu@gmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import airflow_python_sdk
from airflow_python_sdk.api.event_log_api import EventLogApi  # noqa: E501


class TestEventLogApi(unittest.TestCase):
    """EventLogApi unit test stubs"""

    def setUp(self):
        self.api = EventLogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_event_log(self):
        """Test case for create_event_log

        Create event log  # noqa: E501
        """
        pass

    def test_delete_event_log_entry(self):
        """Test case for delete_event_log_entry

        Delete a log entry  # noqa: E501
        """
        pass

    def test_get_event_log(self):
        """Test case for get_event_log

        Get all log entries from event log  # noqa: E501
        """
        pass

    def test_get_event_log_entry(self):
        """Test case for get_event_log_entry

        Get a log entry  # noqa: E501
        """
        pass

    def test_update_event_log_entry(self):
        """Test case for update_event_log_entry

        Update a log entry  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
