"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: zach.z.liu@gmail.com
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "airflow-python-sdk"
VERSION = "0.0.5"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
  "nulltype",
]

setup(
    name=NAME,
    version=VERSION,
    description="Airflow API (Stable)",
    author="Zach Liu",
    author_email="zach.z.liu@gmail.com",
    project_urls={
        "Bug Tracker": "https://github.com/zachliu/airflow-python-sdk/issues",
        "Source Code": "https://github.com/zachliu/airflow-python-sdk",
        "Download": "https://github.com/zachliu/airflow-python-sdk/releases",
        "Documentation": "https://github.com/zachliu/airflow-python-sdk/blob/master/README.md",
    },
    keywords=["OpenAPI", "OpenAPI-Generator", "Airflow API (Stable)"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="MIT",
)
