"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: zach.z.liu@gmail.com
    Generated by: https://openapi-generator.tech
"""

import logging

from test.integration.conftest import BCOLORS


def test_get_dag_run(dag_run_api_setup):
    """Test the /dags/{dag_id}/dagRuns/{dag_run_id} API EP"""
    api_response = dag_run_api_setup.get_dag_run(
        dag_id="example_bash_operator",
        dag_run_id="scheduled__2021-03-03T00:00:00+00:00",
    )
    logging.getLogger().info("%s", api_response)
    print(f"{BCOLORS.OKGREEN}OK{BCOLORS.ENDC}")
