"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: zach.z.liu@gmail.com
    Generated by: https://openapi-generator.tech
"""

import logging
from datetime import datetime

from test.integration.conftest import BCOLORS

from airflow_python_sdk.model.dag_run import DAGRun
from dateutil.parser import parse

def test_trigger_dag_run(dag_run_api_setup):
    """Test the /dags/{dag_id}/dagRuns API EP (post)"""
    time_now = datetime.now().strftime("%Y-%m-%dT%H:%M:%S+00:00")
    dag_run = DAGRun(
        dag_run_id=f"test__{time_now}",
        execution_date=parse(time_now),
        conf={},
    )
    api_response = dag_run_api_setup.post_dag_run(
        dag_id="example_bash_operator",
        dag_run=dag_run,
    )
    logging.getLogger().info("%s", api_response)
    print(f"{BCOLORS.OKGREEN}OK{BCOLORS.ENDC}")
